trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -sL "https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.tgz" | tar -xz -C /usr/local
    export PATH=$PATH:/usr/local/sbt/bin
  displayName: 'Install sbt'

- script: sbt clean compile stage
  displayName: 'Compile Scala Code'

- script: deployment/package.sh
  displayName: 'Package Scala Play Application'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/target/universal'
    Contents: 'VoiceAPP.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: 'drop'
    publishLocation: 'Container'
